### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by malnvenshorn** [linuxgurugamer/CrewRandR#6]
After installing this mod the game becomes nearly unresponsive when opening the astronaut complex and cpu usage goes to 100%. So I had to remove this mod. I tried version 1.1.0.3 of this mod with Kerbal 1.2.2.

**Comment by linuxgurugamer** [comment]
Log file is needed, also, your save file would be useful.

**Comment by linuxgurugamer** [comment]
Oh, there may be an extra dll in the directory.  Look in the Plugins directory, if you see a file called "CrewQueue.dll", delete it.

**Comment by malnvenshorn** [comment]
Removing the CrewQueue.dll improves the situation and the cpu doesn't hit the 100% anymore. But it is still laggy.

Save and log file:
https://ufile.io/iyfe8
https://ufile.io/3p6t5

**Comment by empirogov** [comment]
I'm not sure, but this may be caused by this:
https://github.com/linuxgurugamer/CrewRandR/blob/master/Source/Interface/SpaceCenterModule.cs#L53
Update method called each frame, and there's some performance-heavy things:
1. Searching for GameObjects of type (not very good for performance if taken each frame)
2. Traversing thru each crew container and building new string label for it.

I have no experience with KSP modding, and so far have no solution for (1), but as a quick, but not very professional fix for (2) I can propose this:
```cs
    private float lastUpdated = 0f;

    private const float UPDATE_TRESHOLD = 1f; // UI update period in seconds

    protected override void Update()
        {
            updateThreshold += Time.deltaTime;
            if (astronautComplexSpawned && lastUpdated > UPDATE_THRESHOLD)
            {
                updateACCrewList();
                lastUpdated = 0f;
            }
        }

        private void updateACCrewList ()
        {
            Logging.Debug("AC is spawned...");

            AstronautComplex ac = GameObject.FindObjectOfType<AstronautComplex>();
            if (ac)
            {
                foreach (var s in ac.ScrollListAvailable)
                {
                    Logging.Info("");
                    IEnumerable<CrewListItem> crewItemContainers = GameObject.FindObjectsOfType<CrewListItem>().Where(x => x.GetCrewRef().rosterStatus == ProtoCrewMember.RosterStatus.Available);
                    foreach (CrewListItem crewContainer in crewItemContainers)
                    {
                        if (crewContainer.GetCrewRef().VacationExpiry() - Planetarium.GetUniversalTime() > 0)
                        {
                            Logging.Debug("relabeling: " + crewContainer.GetName());
                            string label = "Ready In: " + Utilities.GetFormattedTime(crewContainer.GetCrewRef().VacationExpiry() - Planetarium.GetUniversalTime());
                            crewContainer.SetLabel(label);
                        }
                    }
                }
            }
        }
```

Sorry, but I have no access to my work PC right now to try this myself :(

**Comment by malnvenshorn** [comment]
I have no experience with KSP modding too. But if @empirogov is right and the update method is called on each frame this might be the root of the issue. Since the ingame time stops after the astronaut complex is loaded the update method must be called only once and not every frame or second. Please correct me if I'm wrong.

**Comment by empirogov** [comment]
@malnvenshorn Completely missed timestop in AC, by bad. Anyways, I'm not sure if data-loading & core KSP UI building in AC is synchronous and UI update by Crew R&R can be taken in some predefined moment (on Start event, or right after changing value of astronautComplexSpawned for example), but if it's true, using astronautComplexSpawned property value change (false -> true) as trigger should be fine, and no periodic updates should be needed.

**Comment by linuxgurugamer** [comment]
You are aware, that the "Update" you reference only does something if the AstronautComplex is spawned?
I may change that to a LateUpdate, but it won't change the underlying issue.

**Comment by malnvenshorn** [comment]
Yes I know that and the problem exists only if I open the astronaut complex.

**Comment by empirogov** [comment]
@linuxgurugamer Of course. Please, correct me if I'm wrong, but as I can see, astronautComplexSpawned flag will be set to true when astronaut complex window opens and stays true till this window closes, so Update method code executes each frame while ac window is displayed.

**Comment by linuxgurugamer** [comment]
Ok, it wasn't clear that you were referring to issues in the Astronaut Complex.
I'll see what I can do to fix this later

**Comment by linuxgurugamer** [comment]
@empirogov Your idea is good, but since time is stopped, you need to do something like this:

```
if (lastUpdated + UPDATE_THRESHOLD <= Time.realtimeSinceStartup)
                {
                    Logging.Debug("AC is spawned...");
                    lastUpdated = Time.realtimeSinceStartup;

```
Also, since new Kerbals can be recruited, and other dismissed, this needs to run, but obviously, not as often.

**Comment by linuxgurugamer** [comment]
Tested and released.  I'm guessing my system is too fast to see the delay, can you please let me know if this fixes it?
Thanks

**Comment by empirogov** [comment]
I've tried last version (just rebuilt it for 1.2.2) and some periodic (very close to 1 second interval of UI update) lags is still present. But overall performance is much better now. Thanks

**Comment by malnvenshorn** [comment]
Yes it is still laggy.

> Also, since new Kerbals can be recruited, and other dismissed, this needs to run, but obviously, not as often.

Why? New recruted Kerbals are available right away and the label don't have to be updated for dismissed Kerbals  either.

**Comment by linuxgurugamer** [comment]
Strange, since it's only running once a second now.
I'll change that to once every 5 seconds in the next release

**Comment by linuxgurugamer** [comment]
The update needs to run to update the time on vacation for those Kerbals who are on vacation.
New update now only does it once every 5 seconds, please let me know how it is

**Comment by malnvenshorn** [comment]
> The update needs to run to update the time on vacation for those Kerbals who are on vacation.

The ingame time doesn't run if the astronaut complex is open. In my opinion the label has to be set only once. I can't see the necessity to update the vacation time periodically. Increasing the update interval doesn't solve the problem. There is always a lag when the update method is called.

**Comment by malnvenshorn** [comment]
My suggestion is something like this:

```
private bool astronautComplexSpawned;
        private bool updateLabelOnce;

        protected override void Awake()
        {
            base.Awake();
            GameEvents.onGUILaunchScreenVesselSelected.Add(onVesselSelected);
            GameEvents.onGUIAstronautComplexSpawn.Add(onGUIAstronautComplexSpawn);
            GameEvents.onGUIAstronautComplexDespawn.Add(onGUIAstronautComplexDespawn);
            GameEvents.onGUILaunchScreenSpawn.Add(onGUILaunchScreenSpawn);
            GameEvents.onGUILaunchScreenDespawn.Add(onGUILaunchScreenDespawn);
            GameEvents.OnCrewmemberHired.Add(onCrewmemberHired);
        }

        protected override void Update()
        {
            if (astronautComplexSpawned && updateLabelOnce)
            {
                Logging.Debug("AC is spawned...");

                AstronautComplex ac = GameObject.FindObjectOfType<AstronautComplex>();
                if (ac && ac.ScrollListAvailable)
                {
                    Logging.Info("");
                    IEnumerable<CrewListItem> crewItemContainers = GameObject.FindObjectsOfType<CrewListItem>().Where(x => x.GetCrewRef().rosterStatus == ProtoCrewMember.RosterStatus.Available);
                    foreach (CrewListItem crewContainer in crewItemContainers)
                    {
                        double remainingVacation = crewContainer.GetCrewRef().VacationExpiry() - Planetarium.GetUniversalTime();
                        if ( remainingVacation > 0)
                        {
                            Logging.Debug("relabeling: " + crewContainer.GetName());
                            string label = "Ready In: " + Utilities.GetFormattedTime(remainingVacation);
                            crewContainer.SetLabel(label);
                        }
                    }

                    updateLabelOnce = false;
                }
            }
        }

        private void onCrewmemberHired(ProtoCrewMember member, int crewCount)
        {
            if (astronautComplexSpawned)
                updateLabelOnce = true;
        }

        private void onGUIAstronautComplexDespawn()
        {
            astronautComplexSpawned = false;
        }

        private void onGUIAstronautComplexSpawn()
        {
            astronautComplexSpawned = true;
            updateLabelOnce = true;
        }
```

The _onCrewmemberHired()_ method is required, because if you dismiss a Kerbal and rehire him again he is still on vacation and the label has to be updated. This is a quick and dirty solution. As I said before I'm not familiar with developing Kerbal mods, therefor there might be better solutions.

**Comment by linuxgurugamer** [comment]
Looks good, I'll merge it with the current code.
And you are absolutely correct about the time being frozen (unless there is a mod installed which will cause time to run, but I'll deal with that if it happens)

Thanks

**Comment by linuxgurugamer** [comment]
Ok, doing it a single time failed, apparently when the LateUpdate is called, KSP isn't finished setting upthe crew list.  So I used your idea, but have it being done 5 tics in a row, which seems to work.
I've seen this in other mods as well, where things aren't set up even though you think they would be
Version 1.1.4, please let me know how it works

**Comment by malnvenshorn** [comment]
There are no lags anymore, as far as I can tell.

During my tests the crew list was ready if `ac.ScrollListAvailable != null`, but maybe this was just a coincidence. A counter might be unreliable, but I can't tell what the best solution is. The documentation is quite sparse.

**Comment by linuxgurugamer** [comment]
Ok.  As I said, I've seen this in several other mods. So I'll leave it for now, unless I hear about ther problems.
Thanks for testing
